name: concrete-cube-tool
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - streamlit>=1.28.0
      - PyMuPDF>=1.23.0
      - pandas>=2.0.0
      - openpyxl>=3.1.0
